---
apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
 name: agent
spec:
  databaseStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
  filesystemStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
  mirrorRegistryRef:
    name: mirrorconfig
  imageStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
  osImages:
    - openshiftVersion: "4.18"
      version: "418.94.202501221327-0" # oc adm release info 4.18.7
      rootFSUrl: 'http://bastion.julin.com/rhcos/rhcos-live-rootfs.x86_64.img'
      url: 'http://bastion.julin.com/rhcos/rhcos-4.18.1-x86_64-live.x86_64.iso'
      cpuArchitecture: "x86_64"
  unauthenticatedRegistries:
    - registry.redhat.io
