---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mirrorconfig
  namespace: multicluster-engine
  labels:
    app: assisted-service
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    XXXXX
    -----END CERTIFICATE-----
  registries.conf: |
    unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]
    [[registry]]
       prefix = ""
       location = "registry.redhat.io/multicluster-engine"
       mirror-by-digest-only = true
       [[registry.mirror]]
       location = "bastion.julin.com:8443/ocp4/multicluster-engine"
    [[registry]]
      prefix = ""
      location = "quay.io/openshift-release-dev/ocp-release"
      [[registry.mirror]]
        location = "bastion.julin.com:8443/ocp4/openshift/release-images"
        pull-from-mirror = "digest-only"
    [[registry]]
      prefix = ""
      location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
      [[registry.mirror]]
        location = "bastion.julin.com:8443/ocp4/openshift/release"
        pull-from-mirror = "digest-only"
    [[registry]]
      prefix = ""
      location = "registry.access.redhat.com/ubi8"
      [[registry.mirror]]
        location = "bastion.julin.com:8443/ocp4/ubi8"
        pull-from-mirror = "digest-only"
    [[registry]]
      prefix = ""
      location = "registry.redhat.io/container-native-virtualization"
      [[registry.mirror]]
        location = "bastion.julin.com:8443/ocp4/container-native-virtualization"
        pull-from-mirror = "digest-only"
    [[registry]]
      prefix = ""
      location = "registry.redhat.io/devworkspace"
      [[registry.mirror]]
        location = "bastion.julin.com:8443/ocp4/devworkspace"
        pull-from-mirror = "digest-only"
    [[registry]]
      prefix = ""
      location = "registry.redhat.io/kube-descheduler-operator"
      [[registry.mirror]]
        location = "bastion.julin.com:8443/ocp4/kube-descheduler-operator"
        pull-from-mirror = "digest-only"
    [[registry]]
      prefix = ""
      location = "registry.redhat.io/lvms4"
      [[registry.mirror]]
        location = "bastion.julin.com:8443/ocp4/lvms4"
        pull-from-mirror = "digest-only"
    [[registry]]
      prefix = ""
      location = "registry.redhat.io/migration-toolkit-virtualization"
      [[registry.mirror]]
        location = "bastion.julin.com:8443/ocp4/migration-toolkit-virtualization"
        pull-from-mirror = "digest-only"
    [[registry]]
      prefix = ""
      location = "registry.redhat.io/multicluster-engine"
      [[registry.mirror]]
        location = "bastion.julin.com:8443/ocp4/multicluster-engine"
        pull-from-mirror = "digest-only"
    [[registry]]
      prefix = ""
      location = "registry.redhat.io/oadp"
      [[registry.mirror]]
        location = "bastion.julin.com:8443/ocp4/oadp"
        pull-from-mirror = "digest-only"
    [[registry]]
      prefix = ""
      location = "registry.redhat.io/odf4"
      [[registry.mirror]]
        location = "bastion.julin.com:8443/ocp4/odf4"
        pull-from-mirror = "digest-only"
    [[registry]]
      prefix = ""
      location = "registry.redhat.io/openshift-update-service"
      [[registry.mirror]]
        location = "bastion.julin.com:8443/ocp4/openshift-update-service"
        pull-from-mirror = "digest-only"
    [[registry]]
      prefix = ""
      location = "registry.redhat.io/openshift4"
      [[registry.mirror]]
        location = "bastion.julin.com:8443/ocp4/openshift4"
        pull-from-mirror = "digest-only"
    [[registry]]
      prefix = ""
      location = "registry.redhat.io/rhacm2"
      [[registry.mirror]]
        location = "bastion.julin.com:8443/ocp4/rhacm2"
        pull-from-mirror = "digest-only"
    [[registry]]
      prefix = ""
      location = "registry.redhat.io/rhel8"
      [[registry.mirror]]
        location = "bastion.julin.com:8443/ocp4/rhel8"
        pull-from-mirror = "digest-only"
    [[registry]]
      prefix = ""
      location = "registry.redhat.io/ubi8"
      [[registry.mirror]]
        location = "bastion.julin.com:8443/ocp4/ubi8"
        pull-from-mirror = "digest-only"
    [[registry]]
      prefix = ""
      location = "registry.redhat.io/ubi9"
      [[registry.mirror]]
        location = "bastion.julin.com:8443/ocp4/ubi9"
        pull-from-mirror = "digest-only"
    [[registry]]
      prefix = ""
      location = "registry.redhat.io/web-terminal"
      [[registry.mirror]]
        location = "bastion.julin.com:8443/ocp4/web-terminal"
        pull-from-mirror = "digest-only"
    [[registry]]
      prefix = ""
      location = "registry.redhat.io/workload-availability"
      [[registry.mirror]]
        location = "bastion.julin.com:8443/ocp4/workload-availability"
        pull-from-mirror = "digest-only"
