---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: cluster1
  namespace: cluster1
  labels:
    cluster.open-cluster-management.io/clusterset: default
    hive.openshift.io/cluster-platform: agent-baremetal
spec:
  baseDomain: julin.com
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: cluster1
    version: v1beta1
  clusterName: cluster1
  controlPlaneConfig:
    servingCertificates: {}
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          agentBareMetal-generated-infraenv-ai-flow: cluster1-cluster1
  pullSecretRef:
    name: pull-secret
