---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: pull-secret
  namespace: cluster1
  labels:
    agent-install.openshift.io/watch: 'true'
    cluster.open-cluster-management.io/backup: cluster
stringData:
  .dockerconfigjson: '{"auths":{"bastion.julin.com:8443":{"auth": "aW5pdDpwYXNzd29yZA=="}}}'
