apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: MultiClusterHub.v1.operator.open-cluster-management.io
  name: open-cluster-management-968zw
  namespace: open-cluster-management
spec:
  targetNamespaces:
  - open-cluster-management
  upgradeStrategy: Default
